### PR TITLE
Fix to --set sonarProperties

### PR DESCRIPTION
**Pull request by pedrofvteixeira**
Hi @rjkernick ( et. al. ), can you please review this contribution ?

**Story**

As a sonarqube admin, I would like to use sonarqube's marketplace at _"my-corp"_ network, so that I may install whatever plugins are deemed relevant for _"my-corp"_ 's needs.

**Issue**

_"my-corp"_ 's  network is behind a firewall, thus requiring `http.proxyHost` and `http.proxyPort` to be set in `sonar.properties`.

However, `--set sonarProperties={ ... }` is not properly injecting the values into sonar.properties.

**Repro path**

1. Install sonarqube. 
  1.1. Example: `helm install -n sonarqube oteemocharts/sonarqube (...) --set replicaCount=1 --set service.type=NodePort --set sonarProperties={ "http.proxyHost=proxy.mycorp.com, http.proxyPort=8080" }`
2. Wait for Sonarqube to be up at <NodePort>, access it at `ip:nodePort`
3. Login as admin, navigate to `Administration > Marketplace`
4. Wait until loading animation ends:
  4.1. **Expected**: list of available plugins
  4.2. **Actual**: no results shown

**Root cause**

1. Do `kubectl logs <pod> -n sonarqube` 
  1.1. Notice the stacktraces: 
```
org.sonar.api.utils.SonarException: Fail to download: https://update.sonarsource.org/update-center.properties (no proxy)
	at org.sonar.core.util.DefaultHttpDownloader.failToDownload(DefaultHttpDownloader.java:155)
	at org.sonar.core.util.DefaultHttpDownloader.readString(DefaultHttpDownloader.java:113)
	at org.sonar.api.utils.UriReader.readString(UriReader.java:69)
	at org.sonar.server.plugins.UpdateCenterClient.init(UpdateCenterClient.java:99)
         (...)
``` 
2. `docker exec` into the sonarqube container: `docker exec -it $( docker ps | grep sonarqube_sonarqube | cut -b -15 ) /bin/bash`
3. `cat conf/sonar.properties`
   3.1. **Expected**: 
```
http.proxyHost=proxy.wal.hds.com
http.proxyPort=8080
```
   3.2. **Actual**: 
```
0=http.proxyHost=proxy.wal.hds.com
1=http.proxyPort=8080
```

With this fix, sonar.properties 's values get properly injected, and consequently, our sonarqube deployment is able to list all marketplace plugins, as well as install them.

### CODE REVIEW

**Comment by rjkernick** [comment]
Please try out the latest chart that was released. I added the ability to use a proxy while downloading plugins in the init containers. https://github.com/Oteemo/charts/pull/34

**Comment by pedrofvteixeira** [comment]
Hi @rjkernick , thanks for the reply. 
I gave it a go once more with the latest chart version:

`helm install -n sonarqube sonarqube oteemocharts/sonarqube --set replicaCount=3 --set service.type=NodePort --set plugins.httpProxy=http://mycorp.com:8080 --set plugins.httpsProxy=http://mycorp.com:8080 --set plugins.install={'https://github.com/checkstyle/sonar-checkstyle/releases/download/4.30/checkstyle-sonar-plugin-4.30.jar'}`

and, while working, I think these ( i.e. latest changes , as well as this open PR ) are serving 2 different use cases, namely:

- **A) Sonarqube HA, with plugin installation across pods** 
   - For this use case, the latest changes do indeed serve the purpose
   - However, while the plugins do appear as installed, there is no marketplace access ( i.e. no list of available plugins ). 
        - This is due to the fact that `conf/sonar.properties` has not been updated with the provided `proxyHost` settings. These have served only as a means to successfully run`install-plugins.sh`

- **B) Sonarqube with `--set sonarProperties={...}` , to update `conf/sonar.properties`**
   - Thus allowing access to the list of available plugins in the markeplace  
   - Allows for the install directly from there


However, mind you, for use case **"B)"**, the server restart required to assume the installed plugin from the marketplace actually means a restart of the webapp within the running container. 
So plugins installed via marketplace would become effective **only** on that specific pod, and **not** on the others ( were we ever to have a replicaCount higher than 1 ).

In light of that, and considering use cases such as having a single Sonarqube pod, I believe the changes in this PR still make sense, as they provide an overall better experience of plugin installation via marketplace.

**Comment by rjkernick** [comment]
I think you may be using the overrides incorrectly. Try to use something like this:

helm install -f overrides.yaml sonarqube oteemocharts/sonarqube

overrides.yaml
```
sonarProperties:
  http.proxyHost: proxy.mycorp.com
  http.proxyPort: 8080
```

**Comment by pedrofvteixeira** [comment]
Hi @rjkernick , sorry for the delay in replying. 
Your suggestion works as intended. 
Thank you.

I am therefore closing this PR as no longer needed, pointing to https://github.com/Oteemo/charts/pull/42#issuecomment-606206939 as the proper solution

**Pull request closed without merging**
