### PR TITLE
Bug fixed at install_plugins.sh in sonar-sonarqube-install-plugins configMap

### PR DESCRIPTION
**Pull request by mrotrebor**
Added validation before remove elements of the folder.
Add new line for each plugin to install.

### CODE REVIEW

**Comment by mrotrebor** [comment]
Issue related: https://github.com/Oteemo/charts/issues/208

**Comment by rjkernick** [comment]
Thanks for the PR. Please increment the version in Chart.yaml and then we can get this merged in.

**Review by rjkernick — APPROVED** [review]

**Comment by rjkernick** [comment]
Thanks for the PR!

**Comment by mrotrebor** [comment]
You're welcome.

**Pull request merged**
