### PR TITLE
Added support for new Ingress ApiVersion in kubernetes 1.22

### LINKED ISSUE #282: [nexus,sonarqube] Ingress Resource not compatible with k8s >1.19
In k8s 1.19 and later the ingress resource created for either nexus or sonarqube is no longer valid. 

This is because of the apiVersion, which should be networking.k8s.io/v1.

Also, the backend definition

```yaml
serviceName: {{ default $serviceName .serviceName }}
servicePort: {{ default $servicePort .servicePort }}
```

should become

```yaml
service:
    name: {{ default $serviceName .serviceName }}
    port: 
        number: {{ default $servicePort .servicePort }}
```

This information can be found in the changelog for 1.19: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.19.md, search for `networking.k8s.io/v1` in this document.

### PR DESCRIPTION
**Pull request by betermieux**
Will fall back to older ApiVersions on older kubernetes clusters.

Fixes #282 and is kind of a duplicate of PR #300 which I haven't seen before. Maybe merge both PR, since I think my templates are more flexible, but I haven't touched sonarqube's chart.

### CODE REVIEW

**Comment by rjkernick** [comment]
Definitely like the pathPrefix being customizable, so please fix the merge conflicts and I can also merge in this change

**Comment by rjkernick** [comment]
#300 Addressed the core concern, but I like some of the customizations here

**Comment by betermieux** [comment]
Will fix the merge conflicts tomorrow.

**Review by rjkernick — APPROVED** [review]

**Comment by jetersen** [comment]
@betermieux thanks for cleaning it up and making it configurable :)

**Pull request merged**
